name: Tests

on:
  push:

jobs:
  kondo:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        check-name: Run clj-kondo
        clj-kondo-args: >-
          --lint
          src
          test
          toucan1/src
          toucan1/test
        github_token: ${{ secrets.GITHUB_TOKEN }}

  tests-clj:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.11.1.1155
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: tests-clj
    - run: clojure -X:test
      name: Run tests

  tests-cljs:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Prepare Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.11.1.1155
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: tests-cljs
    - name: Run tests
      run: yarn run test

  whitespace-linter:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.11.1.1155
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: whitespace-linter
    - run: clojure -T:whitespace-linter
      name: Run whitespace linter

  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: 1.11.1.1155
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        key: check
    - run: clojure -M:check
      name: Check namespaces
